apiVersion: v2
name: eth-validator-watcher
description: Ethereum Validator Watcher - High-performance validator monitoring with Prometheus metrics
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ethereum
  - validator
  - monitoring
  - prometheus
home: https://github.com/enriquemanuel/eth-validator-watcher
sources:
  - https://github.com/enriquemanuel/eth-validator-watcher
maintainers:
  - name: Enrique Valenzuela
    email: enrique@valenzuela.co
